version: "3"
services:
  app:
    image: test-consumer:dev
    restart: always
    environment:
      TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
      TWITTER_BASEURL: ${TWITTER_BASEURL}

    ports:
      - "8091:8091"
    depends_on:
      - "prometheus"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - "prometheus"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    env_file:
      - ./grafana/config.monitoring
    restart: always

