spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false


twitter:
  url: ${TWITTER_BASEURL}
  bearerToken: ${TWITTER_BEARER_TOKEN}
  rules:
    skybet-media: "(@SkyBet) has:media"
    skybet-loading: "loading (@SkyBet)"
    skybet-down: "down (@SkyBet)"
    skybet-stopped: "stopped (@SkyBet)"
    skybet-banned: "banned (@SkyBet)"
    skybet-help-media: "(@SkyBetHelp) has:media"
    skybet-help-loading: "loading (@SkyBetHelp)"
    skybet-help-down: "down (@SkyBetHelp)"
    skybet-help-stopped: "stopped (@SkyBetHelp)"
    skybet-help-banned: "banned (@SkyBetHelp)"
    matt-media: "(@MattchupichuW) has:media"
    matt-loading: "loading (@MattchupichuW)"
    matt-down: "down (@MattchupichuW)"
    matt-stopped: "stopped (@MattchupichuW)"
    matt-banned: "banned (@MattchupichuW)"


management:
  server.port: 8091
  metrics:
    tags:
      app: tojourn
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, livenessstate, mappings, metrics
  endpoint.health.probes.enabled: true
  health.livenessState.enabled: true
  health.readinessState.enabled: true