spring:
  jmx.enabled: true
  application:
    name: "twitter-api"
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://localhost:3306/twitter-api-enhancer"
    username: "root"
    password: "root"

server:
  port: 8080
  shutdown: graceful

# Monitoring
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}